# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backResume:
  # Names
  nameOverride: "back-resume"
  fullnameOverride: "back-resume"

  # Force redeployment
  forceRedeployment: true

  # Replicas
  replicaCount: 1

  # Images
  image:
    repository: europe-west9-docker.pkg.dev/back-resume/resume-repository/back-resume
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  ingress:
    className: nginx
    path: "/back-resume"

  certificate:
    issuerName: letsencrypt-production

  # Service
  service:
    http:
      name: http
      port: 80
    https:
      name: https
      port: 443
    containerPort: 8080

  # Host
  host: clement.duployez.fr

  # Config map
  configMap:
    # Profile
    duployez:
      profile:
        email: c.duployez+resume@gmail.com

    # CORS
    cors:
      allowed_urls: "https://clement.duployez.fr, https://cduployez.github.io, http://localhost:11001, http://localhost:11002"

    # Spring Actuator
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      server:
        port: 8080 # Same as containerPort
        ssl:
          enabled: false # HTTPS is managed at ingress level, not container level

  # Resources
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
      ephemeral_storage: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi
      ephemeral_storage: 256Mi

  # Autoscaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80







