apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.back-resume.fullname" . }}
  labels:
    {{- include "helm-chart.back-resume.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backResume.autoscaling.enabled }}
  replicas: {{ .Values.backResume.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.back-resume.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.backResume.forceRedeployment }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
      labels:
        {{- include "helm-chart.back-resume.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.backResume.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        # image: $LOCATION-docker.pkg.dev/$GCLOUD_PROJECT/hello-repo/helloworld-gke:latest
        image: "{{ .Values.backResume.image.repository }}:{{ .Values.backResume.image.tag | default .Chart.AppVersion }}"
        # This app listens on port 8080 for web traffic by default.
        ports:
          - name: {{ .Values.backResume.service.http.name }}
            containerPort: {{ .Values.backResume.service.containerPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ .Values.backResume.service.http.name }}
          # Should wait 15 seconds before performing the first probe
          initialDelaySeconds: 15
          # The application will have a maximum of 5 minutes (30 * 10 = 300s)
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: {{ .Values.backResume.service.http.name }}
          # Should wait 15 seconds before performing the first probe
          initialDelaySeconds: 15
          # The application will have a maximum of 5 minutes (30 * 10 = 300s)
          periodSeconds: 10
          failureThreshold: 30
        resources:
          requests:
            memory: {{ .Values.backResume.resources.requests.memory }}
            cpu: {{ .Values.backResume.resources.requests.cpu }}
            ephemeral-storage: {{ .Values.backResume.resources.requests.ephemeral_storage }}
          limits:
            memory: {{ .Values.backResume.resources.limits.memory }}
            cpu: {{ .Values.backResume.resources.limits.cpu }}
            ephemeral-storage: {{ .Values.backResume.resources.limits.ephemeral_storage }}
---
