apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-chart.back-resume.fullname" . }}
  labels:
    {{- include "helm-chart.back-resume.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    networking.gke.io/managed-certificates: {{ include "helm-chart.back-resume.fullname" . }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.backResume.ingress.className }}
  rules:
    - host: {{ .Values.backResume.host }}
      http:
        paths:
          - path: {{ .Values.backResume.ingress.path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "helm-chart.back-resume.fullname" . }}
                port:
                  number: {{ .Values.backResume.service.http.port }}
