apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-chart.back-resume.fullname" . }}
  labels:
    {{- include "helm-chart.back-resume.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.backResume.ingress.className }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: {{ .Values.backResume.certificate.issuerName }}
spec:
  tls:
  - hosts:
    - {{ .Values.backResume.host }}
    secretName: {{ include "helm-chart.back-resume.fullname" . }}-tls
  rules:
    - host: {{ .Values.backResume.host }}
      http:
        paths:
          - path: {{ .Values.backResume.ingress.path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "helm-chart.back-resume.fullname" . }}
                port:
                  number: {{ .Values.backResume.service.http.port }}
