apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.back-resume.fullname" . }}
  labels:
    {{- include "helm-chart.back-resume.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "helm-chart.back-resume.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.backResume.service.http.port }}
    targetPort: {{ .Values.backResume.service.containerPort }}
    protocol: TCP
    name: {{ .Values.backResume.service.http.name }}
  - port: {{ .Values.backResume.service.https.port }}
    targetPort: {{ .Values.backResume.service.containerPort }}
    protocol: TCP
    name: {{ .Values.backResume.service.https.name }}
