apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.back-resume.fullname" . }}
  labels:
    {{- include "helm-chart.back-resume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backResume.service.type }}
  selector:
    {{- include "helm-chart.back-resume.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.backResume.service.port }}
    targetPort: {{ .Values.backResume.service.containerPort }}
    protocol: TCP
    name: http
---
